name: pr19
description: "A new Flutter project for notification tracking and SMS automation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization & Formatting
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI & Charts
  fl_chart: ^0.68.0

  # File & Path Utilities
  file_picker: ^8.0.0
  excel: ^4.0.0
  syncfusion_flutter_pdf: ^33.2.13 # 👈 تم تحديث الإصدار لتجنب التعارض مع intl
  url_launcher: ^6.2.5              # 👈 تم فصل السطر بشكل صحيح
  path_provider: ^2.1.2
  path: ^1.8.3

  # Permissions & System
  permission_handler: ^11.3.0

  # Database
  sqflite: ^2.3.0

  # Notifications & Telephony
  flutter_local_notifications: ^17.0.0
  flutter_notification_listener: ^1.4.0
  another_telephony: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # أزل التعليق عن هذا الجزء إذا أردت تضمين ملفات داخل التطبيق (مثل كروت/ملفات إكسل)
  # assets:
  #   - assets/