name: Build Android APK

on:
  push:
    branches:
      - maintest1
  pull_request:
    branches:
      - maintest1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Java 17
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # تثبيت Android SDK 36
      - name: Install Android SDK 36
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-36" \
            "build-tools;36.0.0"

      # Packages
      - name: Install Dependencies
        run: flutter pub get

      # 🔑 1. تفكيك ملف الـ Keystore من GitHub Secrets وخزنه في مجلد android/app
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/kha.jks

      # 🛠️ 2. بناء الـ APK واستدعاء متغيرات البيئة للتوقيع
      - name: Build APK
        run: flutter build apk --release --build-number=${{ github.run_number }}
        env:
          KEYSTORE_PATH: "kha.jks"
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 🔑 3. تنظيف ملف الـ Keystore بعد انتهاء البناء للأمان
      - name: Clean Keystore
        if: always()
        run: rm -f android/app/kha.jks

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
